'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import BackofficePageHeader from '@/components/backoffice/BackofficePageHeader'

type Ticket = { id: string; title: string; status: string; priority: string; created_at: string; reporter?: { username: string } }
const statusLabel: Record<string, string> = { new: 'Nouveau', confirmed: 'Confirmé', in_progress: 'En cours', resolved: 'Résolu', rejected: 'Rejeté' }
export default function BackofficeTicketsPage() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async (value: string) => { setLoading(true); const response = await fetch(`/api/backoffice/tickets${value ? `?status=${value}` : ''}`); if (response.ok) setTickets((await response.json()).data ?? []); setLoading(false) }, [])
  useEffect(() => { void load('') }, [load])
  return <div><BackofficePageHeader eyebrow="Support & qualité" title="Tickets" description="Priorisez les signalements, rassemblez les preuves et donnez une réponse claire aux joueurs." actions={<span className="bo-panel-muted px-3 py-2 text-sm text-slate-400"><strong className="text-slate-100">{tickets.length}</strong> affiché{tickets.length > 1 ? 's' : ''}</span>} /><div className="bo-panel mb-6 flex flex-wrap items-center gap-3 p-4"><label className="flex items-center gap-3"><span className="text-sm font-medium text-slate-300">Afficher</span><select value={status} onChange={(event) => { setStatus(event.target.value); void load(event.target.value) }} className="bo-input w-auto py-2"><option value="">Tous les statuts</option>{['new', 'confirmed', 'in_progress', 'resolved', 'rejected'].map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select></label><p className="text-sm text-slate-500">Les tickets confirmés peuvent ensuite être assignés et résolus.</p></div>{loading ? <div className="bo-panel p-10 text-center text-slate-400">Chargement des tickets…</div> : <div className="bo-panel overflow-hidden"><div className="overflow-x-auto"><table className="bo-table"><thead><tr><th>Signalement</th><th>Joueur</th><th>Statut</th><th>Priorité</th><th>Créé le</th><th aria-label="Ouvrir" /></tr></thead><tbody>{tickets.map((ticket) => <tr key={ticket.id}><td><Link href={`/backoffice/tickets/${ticket.id}`} className="font-semibold text-slate-100 hover:text-emerald-300">{ticket.title}</Link></td><td className="text-slate-400">{ticket.reporter?.username || '—'}</td><td><span className={`bo-status bo-status-${ticket.status}`}>{statusLabel[ticket.status] || ticket.status}</span></td><td><span className={`bo-status ${['high', 'critical'].includes(ticket.priority) ? 'bg-rose-500/15 text-rose-300' : 'bg-slate-800 text-slate-300'}`}>{ticket.priority}</span></td><td className="whitespace-nowrap text-slate-400">{new Date(ticket.created_at).toLocaleDateString('fr-FR')}</td><td className="text-right"><Link href={`/backoffice/tickets/${ticket.id}`} className="font-semibold text-emerald-300 hover:text-emerald-200">Traiter →</Link></td></tr>)}</tbody></table></div>{tickets.length === 0 && <p className="p-10 text-center text-slate-400">Aucun ticket ne correspond à ce filtre.</p>}</div>}</div>
}
