'use client'

import Image from 'next/image'
import Link from 'next/link'
import { use, useCallback, useEffect, useMemo, useState } from 'react'
import BackofficePageHeader from '@/components/backoffice/BackofficePageHeader'

type Medal = { id: string; name: string; description?: string; image_path?: string }
type Row = Record<string, unknown>
type Data = { profile: Record<string, string | number>; achievements: Array<{ achievement_id: string; achievement: Medal }>; allAchievements: Medal[]; games: Row[]; actions: Row[]; tickets: Row[]; audit: Row[]; suggestions: string[] }
type Tab = 'home' | 'stats' | 'achievements' | 'games' | 'audit'
const fallback = '/images/achievements/Bronze/Medals_bronze.webp'
const stats = [['parties_jouees', 'Parties jouées'], ['parties_gagnees', 'Victoires'], ['parties_abandonnees', 'Abandons'], ['meilleur_score', 'Meilleur score'], ['nombre_yams_realises', 'Yams réalisés'], ['serie_victoires_actuelle', 'Série actuelle'], ['meilleure_serie_victoires', 'Meilleure série'], ['xp', 'XP']] as const
const value = (item: unknown, fallbackValue = '—') => item === null || item === undefined || item === '' ? fallbackValue : String(item)

function MedalPicker({ medals, selected, select, label }: { medals: Medal[]; selected?: string; select: (id: string) => void; label: string }) {
  return <div><span className="bo-label">{label}</span><div role="radiogroup" aria-label="Succès à attribuer" className="grid grid-cols-4 gap-2 rounded-xl border border-slate-800 bg-slate-950/35 p-3">{medals.map((medal) => <button key={medal.id} type="button" role="radio" aria-checked={selected === medal.id} onClick={() => select(medal.id)} title={`${medal.name}${medal.description ? ` — ${medal.description}` : ''}`} className={`rounded-xl p-1.5 transition ${selected === medal.id ? 'bg-emerald-400/15 ring-1 ring-emerald-400' : 'hover:bg-slate-800'}`}><span className="block aspect-square overflow-hidden rounded-lg bg-slate-800 p-1"><Image unoptimized src={medal.image_path || fallback} alt="" width={72} height={72} className="size-full object-contain" /></span><span className={`mt-1 block truncate text-center text-[10px] font-semibold ${selected === medal.id ? 'text-emerald-200' : 'text-slate-400'}`}>{medal.name}</span></button>)}</div></div>
}

export default function PlayerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [data, setData] = useState<Data | null>(null); const [tab, setTab] = useState<Tab>('home'); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const [grantId, setGrantId] = useState(''); const [revokeId, setRevokeId] = useState('')
  const load = useCallback(async () => { const response = await fetch(`/api/backoffice/players/${id}`); if (response.ok) setData((await response.json()).data); else setMessage('Impossible de charger cette fiche joueur.') }, [id]); useEffect(() => { void load() }, [load])
  const actionMap = useMemo(() => { const result = new Map<string, Row[]>(); data?.actions.forEach((action) => { const game = String(action.game_id); result.set(game, [...(result.get(game) ?? []), action]) }); return result }, [data?.actions])
  if (!data) return <div className="bo-panel p-10 text-center text-slate-400">Chargement de la fiche joueur…</div>
  const owned = new Set(data.achievements.map((item) => item.achievement_id)); const grantable = data.allAchievements.filter((medal) => !owned.has(medal.id)); const revokeable = data.achievements.map((item) => item.achievement); const grant = grantable.find((medal) => medal.id === grantId) ?? grantable[0]; const revoke = revokeable.find((medal) => medal.id === revokeId) ?? revokeable[0]
  const mutateAchievement = async (event: React.FormEvent<HTMLFormElement>, method: 'POST' | 'DELETE', achievement?: Medal) => { event.preventDefault(); if (!achievement) return; setSaving(true); const form = new FormData(event.currentTarget); const response = await fetch(`/api/backoffice/players/${id}/achievements`, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ achievementId: achievement.id, reason: form.get('reason') }) }); const result = await response.json().catch(() => ({})); setSaving(false); setMessage(response.ok ? (method === 'POST' ? 'Succès attribué et journalisé.' : 'Succès révoqué et journalisé.') : result.error || 'Opération impossible.'); if (response.ok) { setGrantId(''); setRevokeId(''); await load() } }
  const correctStats = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const values = Object.fromEntries(stats.map(([key]) => [key, Number(form.get(key))])); const response = await fetch(`/api/backoffice/players/${id}/stats`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ values, reason: form.get('reason'), ticketId: form.get('ticketId') || undefined, gameId: form.get('gameId') || undefined }) }); const result = await response.json().catch(() => ({})); setSaving(false); setMessage(response.ok ? 'Statistiques corrigées et journalisées.' : result.error || 'Correction impossible.'); if (response.ok) await load() }
  const tabs: Array<[Tab, string]> = [['home', 'Accueil'], ['stats', 'Statistiques'], ['achievements', 'Succès'], ['games', 'Parties'], ['audit', 'Journal']]
  return <div className="space-y-6"><BackofficePageHeader eyebrow="Fiche joueur" title={value(data.profile.username, 'Joueur')} description={value(data.profile.email, 'Email non renseigné')} actions={<Link href="/backoffice/players" className="bo-button-secondary">← Tous les joueurs</Link>} />{message && <p role="status" className="rounded-xl border border-slate-700 bg-slate-800/80 p-4 text-sm">{message}</p>}<nav className="bo-panel flex gap-1 overflow-x-auto p-2" aria-label="Sections de la fiche joueur">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-semibold ${tab === key ? 'bg-emerald-400 text-slate-950' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-100'}`}>{label}</button>)}</nav>
    {tab === 'home' && <section className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Niveau', data.profile.level], ['Parties', data.profile.parties_jouees], ['Victoires', data.profile.parties_gagnees], ['Meilleur score', data.profile.meilleur_score]].map(([label, item]) => <div key={String(label)} className="bo-panel px-5 py-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value(item, '0')}</p></div>)}</div><div className="grid gap-6 xl:grid-cols-2"><div className="bo-panel p-5"><h2 className="text-lg font-bold">Tickets récents</h2><div className="mt-3 divide-y divide-slate-800">{data.tickets.slice(0, 4).map((ticket) => <p key={String(ticket.id)} className="py-3"><strong>{value(ticket.title)}</strong><span className="ml-2 text-sm text-slate-500">{value(ticket.status)}</span></p>)}{data.tickets.length === 0 && <p className="py-3 text-sm text-slate-500">Aucun ticket lié.</p>}</div></div><div className="bo-panel p-5"><h2 className="text-lg font-bold">Dernières interventions</h2><div className="mt-3 divide-y divide-slate-800">{data.audit.slice(0, 4).map((item) => <div key={String(item.id)} className="py-3 text-sm"><strong>{value(item.action)}</strong><p className="text-slate-500">{new Date(String(item.created_at)).toLocaleString('fr-FR')}</p></div>)}{data.audit.length === 0 && <p className="py-3 text-sm text-slate-500">Aucune intervention.</p>}</div></div></div></section>}
    {tab === 'stats' && <section className="bo-panel max-w-5xl p-6"><h2 className="text-xl font-bold">Correction des statistiques</h2><p className="mt-1 text-sm text-slate-400">Chaque correction requiert une justification et est conservée dans le journal.</p><form onSubmit={correctStats} className="mt-5 space-y-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([key, label]) => <label key={key}><span className="bo-label">{label}</span><input name={key} type="number" min="0" defaultValue={Number(data.profile[key] ?? 0)} className="bo-input" /></label>)}</div><div className="grid gap-4 sm:grid-cols-2"><select name="ticketId" className="bo-input"><option value="">Ticket lié (facultatif)</option>{data.tickets.map((ticket) => <option key={String(ticket.id)} value={String(ticket.id)}>{value(ticket.title)}</option>)}</select><select name="gameId" className="bo-input"><option value="">Partie liée (facultative)</option>{data.games.map((game) => <option key={String(game.game_id)} value={String(game.game_id)}>{value(game.game_id)}</option>)}</select></div><textarea name="reason" required minLength={3} placeholder="Motif obligatoire" className="bo-input min-h-20" /><button disabled={saving} className="bo-button-primary">Enregistrer la correction</button></form></section>}
    {tab === 'achievements' && <section className="space-y-6"><div className="bo-panel p-5"><h2 className="text-xl font-bold">Médailles obtenues</h2><div className="mt-4 grid max-h-52 grid-cols-4 gap-3 overflow-auto sm:grid-cols-5 lg:grid-cols-8">{data.achievements.map((item) => <div key={item.achievement_id} title={item.achievement.name}><div className="aspect-square overflow-hidden rounded-full border border-slate-700 bg-slate-800 p-1"><Image unoptimized src={item.achievement.image_path || fallback} alt={item.achievement.name} width={96} height={96} className="size-full object-contain" /></div><p className="mt-1 truncate text-center text-[10px] text-slate-400">{item.achievement.name}</p></div>)}</div>{data.suggestions.length > 0 && <p className="mt-4 text-sm text-amber-300">À vérifier : {data.suggestions.join(', ')}</p>}</div><div className="grid max-w-5xl gap-5 xl:grid-cols-2">{grant && <div className="bo-panel p-5"><h2 className="text-lg font-bold">Attribuer un succès</h2><form onSubmit={(event) => mutateAchievement(event, 'POST', grant)} className="mt-3 space-y-3"><MedalPicker medals={grantable} selected={grant.id} select={setGrantId} label="Choisir une médaille" /><textarea name="reason" required minLength={3} placeholder="Motif obligatoire de l’attribution" className="bo-input min-h-16" /><button disabled={saving} className="bo-button-primary">Attribuer {grant.name}</button></form></div>}{revoke && <div className="bo-panel border-rose-900/60 p-5"><p className="bo-eyebrow text-rose-300">Action exceptionnelle</p><h2 className="mt-1 text-lg font-bold">Révoquer un succès</h2><form onSubmit={(event) => mutateAchievement(event, 'DELETE', revoke)} className="mt-3 space-y-3"><MedalPicker medals={revokeable} selected={revoke.id} select={setRevokeId} label="Choisir la médaille à révoquer" /><textarea name="reason" required minLength={3} placeholder="Motif obligatoire de la révocation" className="bo-input min-h-16" /><button disabled={saving} className="bo-button-danger">Révoquer {revoke.name}</button></form></div>}</div></section>}
    {tab === 'games' && <section className="bo-panel p-6"><h2 className="text-xl font-bold">Parties et preuves</h2><div className="mt-4 space-y-3">{data.games.map((game) => { const gameId = String(game.game_id); const actions = actionMap.get(gameId) ?? []; return <details key={gameId} className="bo-panel-muted px-4 py-3"><summary className="cursor-pointer font-semibold">Partie {gameId.slice(0, 8)}… <span className="ml-2 text-sm font-normal text-slate-400">{value(game.score, '0')} pts · {game.won ? 'victoire' : 'défaite'}</span></summary>{actions.length ? <ol className="mt-3 space-y-2 text-sm text-slate-300">{actions.map((action) => <li key={String(action.id)}>Tour {value(action.turn_number)} · {value(action.category)} · dés [{Array.isArray(action.dice_values) ? action.dice_values.join(', ') : '—'}] · <strong className="text-emerald-300">+{value(action.score, '0')}</strong></li>)}</ol> : <p className="mt-3 text-sm text-amber-300">Chronologie détaillée indisponible.</p>}</details> })}{data.games.length === 0 && <p className="text-slate-500">Aucune partie récente.</p>}</div></section>}
    {tab === 'audit' && <section className="bo-panel max-w-5xl p-6"><h2 className="text-xl font-bold">Journal d’intervention</h2><div className="mt-3 divide-y divide-slate-800">{data.audit.map((item) => <div key={String(item.id)} className="py-4"><strong>{value(item.action)}</strong><p className="mt-1 text-sm text-slate-500">{new Date(String(item.created_at)).toLocaleString('fr-FR')}</p>{Boolean(item.reason) && <p className="mt-1 text-sm text-slate-400">{String(item.reason)}</p>}</div>)}{data.audit.length === 0 && <p className="py-4 text-slate-500">Aucune intervention enregistrée.</p>}</div></section>}
  </div>
}
