'use client'

import Image from 'next/image'
import Link from 'next/link'
import { use, useCallback, useEffect, useState } from 'react'
import BackofficePageHeader from '@/components/backoffice/BackofficePageHeader'

type Medal = { id: string; name: string; description?: string; image_path?: string }
type Item = { achievement_id: string; achievement: Medal }
type Row = Record<string, unknown>
type Data = { profile: Record<string, string | number>; achievements: Item[]; allAchievements: Medal[]; games: Row[]; tickets: Row[]; audit: Row[]; suggestions: string[] }
const fallback = '/images/achievements/Bronze/Medals_bronze.webp'
const statFields = [['parties_jouees', 'Parties jouées'], ['parties_gagnees', 'Victoires'], ['parties_abandonnees', 'Abandons'], ['meilleur_score', 'Meilleur score'], ['nombre_yams_realises', 'Yams réalisés'], ['serie_victoires_actuelle', 'Série actuelle'], ['meilleure_serie_victoires', 'Meilleure série'], ['xp', 'XP']] as const
const display = (value: unknown, fallbackValue = '—') => value === null || value === undefined || value === '' ? fallbackValue : String(value)

function MedalPicker({ medals, selectedId, onSelect, label }: { medals: Medal[]; selectedId?: string; onSelect: (id: string) => void; label: string }) {
  return <div><span className="bo-label">{label}</span><div role="radiogroup" aria-label="Succès à attribuer" className="grid grid-cols-4 gap-2 rounded-xl border border-slate-800 bg-slate-950/35 p-3 sm:grid-cols-5 xl:grid-cols-4">{medals.map((medal) => { const selected = medal.id === selectedId; return <button key={medal.id} type="button" role="radio" aria-checked={selected} onClick={() => onSelect(medal.id)} title={`${medal.name}${medal.description ? ` — ${medal.description}` : ''}`} className={`group rounded-xl p-1.5 transition ${selected ? 'bg-emerald-400/15 ring-1 ring-emerald-400' : 'hover:bg-slate-800'}`}><span className="block aspect-square overflow-hidden rounded-lg bg-slate-800 p-1"><Image unoptimized src={medal.image_path || fallback} alt="" width={80} height={80} className="size-full object-contain" /></span><span className={`mt-1 block truncate text-center text-[10px] font-semibold ${selected ? 'text-emerald-200' : 'text-slate-400'}`}>{medal.name}</span></button> })}</div></div>
}

export default function PlayerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [data, setData] = useState<Data | null>(null); const [message, setMessage] = useState(''); const [selectedGrant, setSelectedGrant] = useState(''); const [selectedRevoke, setSelectedRevoke] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { const response = await fetch(`/api/backoffice/players/${id}`); if (response.ok) setData((await response.json()).data); else setMessage('Impossible de charger cette fiche joueur.') }, [id]); useEffect(() => { void load() }, [load])
  if (!data) return <div className="bo-panel p-10 text-center text-slate-400">Chargement de la fiche joueur…</div>
  const owned = new Set(data.achievements.map((item) => item.achievement_id)); const grantable = data.allAchievements.filter((medal) => !owned.has(medal.id)); const revokeMedals = data.achievements.map((item) => item.achievement); const grant = grantable.find((medal) => medal.id === selectedGrant) ?? grantable[0]; const revoke = revokeMedals.find((medal) => medal.id === selectedRevoke) ?? revokeMedals[0]
  const mutate = async (event: React.FormEvent<HTMLFormElement>, method: 'POST' | 'DELETE', achievementId?: string) => { event.preventDefault(); if (!achievementId) return; setSaving(true); setMessage(''); const form = new FormData(event.currentTarget); const response = await fetch(`/api/backoffice/players/${id}/achievements`, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ achievementId, reason: form.get('reason') }) }); const result = await response.json().catch(() => ({})); setSaving(false); setMessage(response.ok ? (method === 'POST' ? 'Succès attribué et journalisé.' : 'Succès révoqué et journalisé.') : result.error || 'Opération impossible.'); if (response.ok) { setSelectedGrant(''); setSelectedRevoke(''); await load() } }
  const correctStats = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const values = Object.fromEntries(statFields.map(([key]) => [key, Number(form.get(key))])); const response = await fetch(`/api/backoffice/players/${id}/stats`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ values, reason: form.get('reason'), ticketId: form.get('ticketId') || undefined, gameId: form.get('gameId') || undefined }) }); const result = await response.json().catch(() => ({})); setSaving(false); setMessage(response.ok ? 'Statistiques corrigées et journalisées.' : result.error || 'Correction impossible.'); if (response.ok) await load() }
  return <div className="space-y-6"><BackofficePageHeader eyebrow="Fiche joueur" title={display(data.profile.username, 'Joueur')} description={display(data.profile.email, 'Email non renseigné')} actions={<Link href="/backoffice/players" className="bo-button-secondary">← Tous les joueurs</Link>} />{message && <p role="status" className="rounded-xl border border-slate-700 bg-slate-800/80 p-4 text-sm">{message}</p>}<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Niveau', data.profile.level], ['Parties', data.profile.parties_jouees], ['Victoires', data.profile.parties_gagnees], ['Meilleur score', data.profile.meilleur_score]].map(([label, value]) => <div key={String(label)} className="bo-panel px-5 py-4"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{display(value, '0')}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(20rem,.8fr)]"><div className="bo-panel p-6"><h2 className="text-xl font-bold">Correction des statistiques</h2><form onSubmit={correctStats} className="mt-5 space-y-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{statFields.map(([key, label]) => <label key={key}><span className="bo-label">{label}</span><input name={key} type="number" min="0" defaultValue={Number(data.profile[key] ?? 0)} className="bo-input" /></label>)}</div><textarea name="reason" required minLength={3} placeholder="Motif obligatoire" className="bo-input min-h-20" /><button disabled={saving} className="bo-button-primary">Enregistrer la correction</button></form></div>
      <aside className="bo-panel p-6"><h2 className="text-xl font-bold">Succès obtenus</h2><div className="mt-4 grid max-h-52 grid-cols-4 gap-3 overflow-auto sm:grid-cols-5 xl:grid-cols-4">{data.achievements.map((item) => <div key={item.achievement_id} title={item.achievement.name}><div className="aspect-square overflow-hidden rounded-full border border-slate-700 bg-slate-800 p-1"><Image unoptimized src={item.achievement.image_path || fallback} alt={item.achievement.name} width={96} height={96} className="size-full object-contain" /></div><p className="mt-1 truncate text-center text-[10px] text-slate-400">{item.achievement.name}</p></div>)}</div>{data.suggestions.length > 0 && <p className="mt-4 text-sm text-amber-300">À vérifier : {data.suggestions.join(', ')}</p>}</aside></section>
    {grant && <section className="bo-panel p-6"><h2 className="text-xl font-bold">Attribuer un succès</h2><form onSubmit={(event) => mutate(event, 'POST', grant.id)} className="mt-4 space-y-4"><MedalPicker medals={grantable} selectedId={grant.id} onSelect={setSelectedGrant} label="Choisir une médaille" /><textarea name="reason" required minLength={3} placeholder="Motif obligatoire de l’attribution" className="bo-input min-h-20" /><button disabled={saving} className="bo-button-primary">Attribuer {grant.name}</button></form></section>}
    {revoke && <section className="bo-panel border-rose-900/60 p-6"><p className="bo-eyebrow text-rose-300">Action exceptionnelle</p><h2 className="mt-1 text-xl font-bold">Révoquer un succès</h2><p className="mt-1 text-sm text-slate-400">La médaille choisie est retirée immédiatement ; le motif reste dans le journal d’intervention.</p><form onSubmit={(event) => mutate(event, 'DELETE', revoke.id)} className="mt-4 space-y-4"><MedalPicker medals={revokeMedals} selectedId={revoke.id} onSelect={setSelectedRevoke} label="Choisir la médaille à révoquer" /><textarea name="reason" required minLength={3} placeholder="Motif obligatoire de la révocation" className="bo-input min-h-20" /><button disabled={saving} className="bo-button-danger">Révoquer {revoke.name}</button></form></section>}
    <section className="grid gap-6 xl:grid-cols-2"><div className="bo-panel p-6"><h2 className="text-xl font-bold">Tickets liés</h2><div className="mt-3 divide-y divide-slate-800">{data.tickets.map((ticket) => <p key={String(ticket.id)} className="py-3"><strong>{display(ticket.title)}</strong><span className="ml-2 text-sm text-slate-500">{display(ticket.status)}</span></p>)}</div></div><div className="bo-panel p-6"><h2 className="text-xl font-bold">Journal d’intervention</h2><div className="mt-3 max-h-80 divide-y divide-slate-800 overflow-auto">{data.audit.map((item) => <div key={String(item.id)} className="py-3 text-sm"><strong>{display(item.action)}</strong><p className="text-slate-500">{new Date(String(item.created_at)).toLocaleString('fr-FR')}</p>{Boolean(item.reason) && <p className="text-slate-400">{String(item.reason)}</p>}</div>)}</div></div></section></div>
}
