'use client'

import { useEffect, useState } from 'react'

type User={id:string;email:string;role:string;disabled_at:string|null};type Device={id:string;user_id:string;label:string;last_used_at:string;revoked_at:string|null;user?:{email:string}}
export default function TeamPage(){const [users,setUsers]=useState<User[]>([]);const [devices,setDevices]=useState<Device[]>([]);const [message,setMessage]=useState('');const [deviceLink,setDeviceLink]=useState('');async function load(){const [team,deviceResponse]=await Promise.all([fetch('/api/backoffice/team/invitations'),fetch('/api/backoffice/team/devices')]);if(team.ok)setUsers((await team.json()).users??[]);if(deviceResponse.ok)setDevices((await deviceResponse.json()).data??[])}useEffect(()=>{void load()},[])
async function invite(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch('/api/backoffice/team/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),role:form.get('role')})});setMessage(response.ok?'Invitation envoyée.':(await response.json()).error);if(response.ok){event.currentTarget.reset();await load()}}
async function authorize(userId:string){setDeviceLink('');const response=await fetch('/api/backoffice/team/devices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId})});const result=await response.json().catch(()=>({}));setMessage(response.ok?(result.accessUrl?'Lien local créé.':'Nouveau lien envoyé.'):result.error);if(result.accessUrl)setDeviceLink(result.accessUrl)}async function revoke(id:string){if(!confirm('Révoquer cet appareil ?'))return;await fetch(`/api/backoffice/team/devices?id=${id}`,{method:'DELETE'});await load()}
async function toggleUser(user:User){if(!confirm(user.disabled_at?'Réactiver ce compte ?':'Désactiver ce compte et révoquer ses appareils ?'))return;const response=await fetch(`/api/backoffice/team/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({disabled:!user.disabled_at})});setMessage(response.ok?'Compte mis à jour.':(await response.json()).error);if(response.ok)await load()}
async function changeRole(user:User,role:string){if(role===user.role)return;const response=await fetch(`/api/backoffice/team/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});setMessage(response.ok?'Rôle mis à jour et sessions révoquées.':(await response.json()).error);if(response.ok)await load()}
return <div className="space-y-8"><h1 className="text-3xl font-bold">Équipe et appareils</h1>{message&&<p className="rounded bg-slate-800 p-3">{message}</p>}{deviceLink&&<p className="rounded border border-amber-500 bg-amber-950/40 p-3 break-all">Lien local à usage unique : <a href={deviceLink} className="text-amber-300 underline">ouvrir sur le nouvel appareil</a></p>}<form onSubmit={invite} className="flex flex-wrap gap-3 rounded border border-slate-700 p-5"><input name="email" type="email" required placeholder="Email" className="min-w-72 flex-1 rounded bg-slate-800 p-3"/><select name="role" className="rounded bg-slate-800 p-3"><option value="operator">Opérateur</option><option value="admin">Admin</option></select><button className="rounded bg-emerald-500 px-5 font-bold text-slate-950">Inviter</button></form><section><h2 className="text-xl font-bold mb-3">Comptes</h2>{users.map((user)=><div key={user.id} className="flex flex-wrap items-center gap-3 border-b border-slate-800 py-3"><span>{user.email}{user.disabled_at?' · désactivé':''}</span><select aria-label={`Rôle de ${user.email}`} value={user.role} onChange={(event)=>changeRole(user,event.target.value)} className="rounded bg-slate-800 p-2"><option value="operator">Opérateur</option><option value="admin">Admin</option></select><button onClick={()=>authorize(user.id)} className="ml-auto rounded border border-slate-600 px-3 py-2">Autoriser un appareil</button><button onClick={()=>toggleUser(user)} className="rounded bg-red-900 px-3 py-2">{user.disabled_at?'Réactiver':'Désactiver'}</button></div>)}</section><section><h2 className="text-xl font-bold mb-3">Appareils</h2>{devices.map((device)=><div key={device.id} className="flex items-center gap-3 border-b border-slate-800 py-3"><span>{device.user?.email||device.user_id}</span><span className="text-sm text-slate-400">{device.label} · {new Date(device.last_used_at).toLocaleString('fr-FR')}</span>{!device.revoked_at&&<button onClick={()=>revoke(device.id)} className="ml-auto rounded bg-red-900 px-3 py-2">Révoquer</button>}</div>)}</section></div>}
